"""altercolumn

Revision ID: 74e9350f78b7
Revises: 83f43149ebfa
Create Date: 2022-10-02 17:35:44.259750

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "74e9350f78b7"
down_revision = "83f43149ebfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "field", server_default=None, new_column_name="fields")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
